/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazGrafica.ventanasafiliados;

import excepciones.DNIException;
import excepciones.Metodos;
import excepciones.VerficarCampoVacioException;
import clasessimples.Afiliado;
import java.time.LocalDate;
import java.time.Month;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import sistema.de.emergencia.medica.GestionHospital;

/**
 *
 * @author Miguel
 */
public class FormularioAltaAfiliado extends javax.swing.JFrame {

    GestionHospital ventanaFormularioAltaEmpleado;
    
    public FormularioAltaAfiliado(GestionHospital gh) {
        initComponents();
        ventanaFormularioAltaEmpleado = gh;
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        setIconImage (new ImageIcon(getClass().getResource("/Imagenes_Iconos/red-38673_960_720.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombreaa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        apellidoaa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dniaa = new javax.swing.JTextField();
        sexoaa = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        diaFechaNacimientoaa = new javax.swing.JTextField();
        mesFechaNacimientoaa = new javax.swing.JTextField();
        anioFechaNacimientoaa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        diaFechaPagoaa = new javax.swing.JTextField();
        mesFechaPagoaa = new javax.swing.JTextField();
        anioFechaPagoaa = new javax.swing.JTextField();
        inscribir = new javax.swing.JButton();
        numero = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alta Afiliado");
        setMaximumSize(new java.awt.Dimension(600, 600));
        setMinimumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(600, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setText("NOMBRE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(41, 59, 60, 14);

        nombreaa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreaaKeyTyped(evt);
            }
        });
        getContentPane().add(nombreaa);
        nombreaa.setBounds(41, 79, 232, 20);

        jLabel2.setText("APELLIDO");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(336, 59, 70, 14);

        apellidoaa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                apellidoaaKeyTyped(evt);
            }
        });
        getContentPane().add(apellidoaa);
        apellidoaa.setBounds(336, 79, 176, 20);

        jLabel3.setText("DNI");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(43, 146, 40, 14);

        dniaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dniaaActionPerformed(evt);
            }
        });
        dniaa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dniaaKeyTyped(evt);
            }
        });
        getContentPane().add(dniaa);
        dniaa.setBounds(41, 166, 232, 20);

        sexoaa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino\t", "Femenino", " " }));
        sexoaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexoaaActionPerformed(evt);
            }
        });
        getContentPane().add(sexoaa);
        sexoaa.setBounds(336, 166, 87, 20);

        jLabel4.setText("SEXO");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(336, 146, 50, 14);

        diaFechaNacimientoaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaFechaNacimientoaaActionPerformed(evt);
            }
        });
        diaFechaNacimientoaa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                diaFechaNacimientoaaKeyTyped(evt);
            }
        });
        getContentPane().add(diaFechaNacimientoaa);
        diaFechaNacimientoaa.setBounds(41, 281, 30, 20);

        mesFechaNacimientoaa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mesFechaNacimientoaaKeyTyped(evt);
            }
        });
        getContentPane().add(mesFechaNacimientoaa);
        mesFechaNacimientoaa.setBounds(81, 281, 30, 20);

        anioFechaNacimientoaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anioFechaNacimientoaaActionPerformed(evt);
            }
        });
        anioFechaNacimientoaa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                anioFechaNacimientoaaKeyTyped(evt);
            }
        });
        getContentPane().add(anioFechaNacimientoaa);
        anioFechaNacimientoaa.setBounds(121, 281, 61, 20);

        jLabel5.setText("DD     /     MM     /     AAAA");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(41, 261, 141, 14);

        jLabel6.setText("FECHA DE NACIMIENTO");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(41, 241, 140, 14);

        jLabel7.setText("DD     /     MM     /     AAAA");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(336, 261, 141, 14);

        jLabel8.setText("FECHA DE INSCRIPCION");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(336, 241, 140, 14);

        diaFechaPagoaa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                diaFechaPagoaaKeyTyped(evt);
            }
        });
        getContentPane().add(diaFechaPagoaa);
        diaFechaPagoaa.setBounds(336, 281, 30, 20);

        mesFechaPagoaa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mesFechaPagoaaKeyTyped(evt);
            }
        });
        getContentPane().add(mesFechaPagoaa);
        mesFechaPagoaa.setBounds(376, 281, 30, 20);

        anioFechaPagoaa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                anioFechaPagoaaKeyTyped(evt);
            }
        });
        getContentPane().add(anioFechaPagoaa);
        anioFechaPagoaa.setBounds(418, 281, 57, 20);

        inscribir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Iconos/guardar.png"))); // NOI18N
        inscribir.setText("INSCRIBIR");
        inscribir.setContentAreaFilled(false);
        inscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscribirActionPerformed(evt);
            }
        });
        getContentPane().add(inscribir);
        inscribir.setBounds(41, 385, 150, 57);

        numero.setEditable(false);
        numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroActionPerformed(evt);
            }
        });
        numero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numeroKeyTyped(evt);
            }
        });
        getContentPane().add(numero);
        numero.setBounds(41, 330, 232, 20);

        jLabel9.setText("NUMERO DE AFILIADO");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(41, 310, 140, 14);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Iconos/TRAS.png"))); // NOI18N
        jButton6.setText("VOLVER");
        jButton6.setContentAreaFilled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(389, 385, 123, 57);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreaaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreaaKeyTyped
        char c = evt.getKeyChar();
        
        if(Character.isDigit(c)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingrese solo letras","Error", JOptionPane.ERROR_MESSAGE);
        }
        else if((int)evt.getKeyChar()>32 && (int)evt.getKeyChar()<=47
             ||(int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=64
             || (int)evt.getKeyChar()>=91 && (int)evt.getKeyChar()<=96
             || (int)evt.getKeyChar()>=123 && (int)evt.getKeyChar()<=255)
    {
         getToolkit().beep();
         evt.consume();
         JOptionPane.showMessageDialog(this, "Ingrese solo letras","Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_nombreaaKeyTyped

    private void apellidoaaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apellidoaaKeyTyped
        char c = evt.getKeyChar();
        
        if(Character.isDigit(c)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingrese solo letras","Error", JOptionPane.ERROR_MESSAGE);
        }
        else if((int)evt.getKeyChar()>32 && (int)evt.getKeyChar()<=47
             ||(int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=64
             || (int)evt.getKeyChar()>=91 && (int)evt.getKeyChar()<=96
             || (int)evt.getKeyChar()>=123 && (int)evt.getKeyChar()<=255)
    {
         getToolkit().beep();
         evt.consume();
         JOptionPane.showMessageDialog(this, "Ingrese solo letras","Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_apellidoaaKeyTyped

    private void dniaaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dniaaKeyTyped

        char C= evt.getKeyChar();
     if(Character.isLetter(C))
     {
         getToolkit().beep();
         evt.consume();
         JOptionPane.showMessageDialog(this, "Ingrese solo numeros","Error", JOptionPane.ERROR_MESSAGE);
         dniaa.setCursor(null);
     }
     else if((int)evt.getKeyChar()>32 && (int)evt.getKeyChar()<=47
             ||(int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=64
             || (int)evt.getKeyChar()>=91 && (int)evt.getKeyChar()<=96
             || (int)evt.getKeyChar()>=123 && (int)evt.getKeyChar()<=255)
    {
         getToolkit().beep();
         evt.consume();
         JOptionPane.showMessageDialog(this, "Ingrese solo numeros","Error", JOptionPane.ERROR_MESSAGE);
         dniaa.setCursor(null);
     }
     else if(dniaa.getText().length() >= 8){
         evt.consume();
         getToolkit().beep();
         JOptionPane.showMessageDialog(this, "Longitud maxima de ocho caracteres","Error", JOptionPane.ERROR_MESSAGE);
         
     }
    }//GEN-LAST:event_dniaaKeyTyped

    private void diaFechaNacimientoaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaFechaNacimientoaaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diaFechaNacimientoaaActionPerformed

    private void diaFechaNacimientoaaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_diaFechaNacimientoaaKeyTyped

        char C= evt.getKeyChar();
     if(Character.isLetter(C))
     {
         getToolkit().beep();
         evt.consume();
         JOptionPane.showMessageDialog(this, "Ingrese solo numeros","Error", JOptionPane.ERROR_MESSAGE);
         diaFechaNacimientoaa.setCursor(null);
     }
     else if((int)evt.getKeyChar()>32 && (int)evt.getKeyChar()<=47
             ||(int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=64
             || (int)evt.getKeyChar()>=91 && (int)evt.getKeyChar()<=96
             || (int)evt.getKeyChar()>=123 && (int)evt.getKeyChar()<=255)
    {
         getToolkit().beep();
         evt.consume();
         JOptionPane.showMessageDialog(this, "Ingrese solo numeros","Error", JOptionPane.ERROR_MESSAGE);
         diaFechaNacimientoaa.setCursor(null);
     }
     else if(diaFechaNacimientoaa.getText().length() >= 2){
         evt.consume();
         getToolkit().beep();
         JOptionPane.showMessageDialog(this, "Longitud maxima de dos caracteres","Error", JOptionPane.ERROR_MESSAGE);
         diaFechaNacimientoaa.setCursor(null);
     }
    }//GEN-LAST:event_diaFechaNacimientoaaKeyTyped

    private void mesFechaNacimientoaaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mesFechaNacimientoaaKeyTyped

        char C= evt.getKeyChar();
     if(Character.isLetter(C))
     {
         getToolkit().beep();
         evt.consume();
         JOptionPane.showMessageDialog(this, "Ingrese solo numeros","Error", JOptionPane.ERROR_MESSAGE);
         mesFechaNacimientoaa.setCursor(null);
     }
     else if((int)evt.getKeyChar()>32 && (int)evt.getKeyChar()<=47
             ||(int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=64
             || (int)evt.getKeyChar()>=91 && (int)evt.getKeyChar()<=96
             || (int)evt.getKeyChar()>=123 && (int)evt.getKeyChar()<=255)
    {
         getToolkit().beep();
         evt.consume();
         JOptionPane.showMessageDialog(this, "Ingrese solo numeros","Error", JOptionPane.ERROR_MESSAGE);
         mesFechaNacimientoaa.setCursor(null);
     }
     else if(mesFechaNacimientoaa.getText().length() >= 2){
         evt.consume();
         getToolkit().beep();
         JOptionPane.showMessageDialog(this, "Longitud maxima de dos caracteres","Error", JOptionPane.ERROR_MESSAGE);
         mesFechaNacimientoaa.setCursor(null);
     }
    }//GEN-LAST:event_mesFechaNacimientoaaKeyTyped

    private void anioFechaNacimientoaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anioFechaNacimientoaaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anioFechaNacimientoaaActionPerformed

    private void anioFechaPagoaaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_anioFechaPagoaaKeyTyped

                char C= evt.getKeyChar();
     if(Character.isLetter(C))
     {
         getToolkit().beep();
         evt.consume();
         JOptionPane.showMessageDialog(this, "Ingrese solo numeros","Error", JOptionPane.ERROR_MESSAGE);
         anioFechaPagoaa.setCursor(null);
     }
     else if((int)evt.getKeyChar()>32 && (int)evt.getKeyChar()<=47
             ||(int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=64
             || (int)evt.getKeyChar()>=91 && (int)evt.getKeyChar()<=96
             || (int)evt.getKeyChar()>=123 && (int)evt.getKeyChar()<=255)
    {
         getToolkit().beep();
         evt.consume();
         JOptionPane.showMessageDialog(this, "Ingrese solo numeros","Error", JOptionPane.ERROR_MESSAGE);
         anioFechaPagoaa.setCursor(null);
     }
     else if(anioFechaPagoaa.getText().length() >= 4){
         evt.consume();
         getToolkit().beep();
         JOptionPane.showMessageDialog(this, "Longitud maxima de cuatro caracteres","Error", JOptionPane.ERROR_MESSAGE);
         anioFechaPagoaa.setCursor(null);
     }
    }//GEN-LAST:event_anioFechaPagoaaKeyTyped

    private void anioFechaNacimientoaaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_anioFechaNacimientoaaKeyTyped

                char C= evt.getKeyChar();
     if(Character.isLetter(C))
     {
         getToolkit().beep();
         evt.consume();
         JOptionPane.showMessageDialog(this, "Ingrese solo numeros","Error", JOptionPane.ERROR_MESSAGE);
         anioFechaNacimientoaa.setCursor(null);
     }
     else if((int)evt.getKeyChar()>32 && (int)evt.getKeyChar()<=47
             ||(int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=64
             || (int)evt.getKeyChar()>=91 && (int)evt.getKeyChar()<=96
             || (int)evt.getKeyChar()>=123 && (int)evt.getKeyChar()<=255)
    {
         getToolkit().beep();
         evt.consume();
         JOptionPane.showMessageDialog(this, "Ingrese solo numeros","Error", JOptionPane.ERROR_MESSAGE);
         anioFechaNacimientoaa.setCursor(null);
     }
     else if(anioFechaNacimientoaa.getText().length() >= 4){
         evt.consume();
         getToolkit().beep();
         JOptionPane.showMessageDialog(this, "Longitud maxima de cuatro caracteres","Error", JOptionPane.ERROR_MESSAGE);
         anioFechaNacimientoaa.setCursor(null);
     }
    }//GEN-LAST:event_anioFechaNacimientoaaKeyTyped

    private void diaFechaPagoaaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_diaFechaPagoaaKeyTyped

                char C= evt.getKeyChar();
     if(Character.isLetter(C))
     {
         getToolkit().beep();
         evt.consume();
         JOptionPane.showMessageDialog(this, "Ingrese solo numeros","Error", JOptionPane.ERROR_MESSAGE);
         diaFechaPagoaa.setCursor(null);
     }
     else if((int)evt.getKeyChar()>32 && (int)evt.getKeyChar()<=47
             ||(int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=64
             || (int)evt.getKeyChar()>=91 && (int)evt.getKeyChar()<=96
             || (int)evt.getKeyChar()>=123 && (int)evt.getKeyChar()<=255)
    {
         getToolkit().beep();
         evt.consume();
         JOptionPane.showMessageDialog(this, "Ingrese solo numeros","Error", JOptionPane.ERROR_MESSAGE);
         diaFechaPagoaa.setCursor(null);
     }
     else if(diaFechaPagoaa.getText().length() >= 2){
         evt.consume();
         getToolkit().beep();
         JOptionPane.showMessageDialog(this, "Longitud maxima de dos caracteres","Error", JOptionPane.ERROR_MESSAGE);
         diaFechaPagoaa.setCursor(null);
     }
    }//GEN-LAST:event_diaFechaPagoaaKeyTyped

    private void mesFechaPagoaaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mesFechaPagoaaKeyTyped

                char C= evt.getKeyChar();
     if(Character.isLetter(C))
     {
         getToolkit().beep();
         evt.consume();
         JOptionPane.showMessageDialog(this, "Ingrese solo numeros","Error", JOptionPane.ERROR_MESSAGE);
         mesFechaPagoaa.setCursor(null);
     }
     else if((int)evt.getKeyChar()>32 && (int)evt.getKeyChar()<=47
             ||(int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=64
             || (int)evt.getKeyChar()>=91 && (int)evt.getKeyChar()<=96
             || (int)evt.getKeyChar()>=123 && (int)evt.getKeyChar()<=255)
    {
         getToolkit().beep();
         evt.consume();
         JOptionPane.showMessageDialog(this, "Ingrese solo numeros","Error", JOptionPane.ERROR_MESSAGE);
         mesFechaPagoaa.setCursor(null);
     }
     else if(mesFechaPagoaa.getText().length() >= 2){
         evt.consume();
         getToolkit().beep();
         JOptionPane.showMessageDialog(this, "Longitud maxima de dos caracteres","Error", JOptionPane.ERROR_MESSAGE);
         mesFechaPagoaa.setCursor(null);
     }
    }//GEN-LAST:event_mesFechaPagoaaKeyTyped

    private void inscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscribirActionPerformed
        try{
            
        Integer dn,mn,an,dp,mp,ap;
        dn= Integer.parseInt(diaFechaNacimientoaa.getText());
        mn=Integer.parseInt(mesFechaNacimientoaa.getText());
        an=Integer.parseInt(anioFechaNacimientoaa.getText());
        dp=Integer.parseInt(diaFechaPagoaa.getText());
        mp=Integer.parseInt(mesFechaPagoaa.getText());
        ap=Integer.parseInt(anioFechaPagoaa.getText());
        String sexo = (String) sexoaa.getSelectedItem();
        LocalDate fechaNacimiento = LocalDate.of(an, mn, dn);
        LocalDate fechaPago = LocalDate.of(ap, mp, dp);
        Integer dni = Integer.parseInt(this.dniaa.getText());
        ventanaFormularioAltaEmpleado.verificarDatos(dniaa.getText(),nombreaa.getText(),apellidoaa.getText(),diaFechaNacimientoaa.getText(),String.valueOf(mesFechaNacimientoaa.getText()),String.valueOf(anioFechaNacimientoaa.getText()));  

        Metodos.validarDNI(dni);
        boolean  encontrado = ventanaFormularioAltaEmpleado.validarDni(dni);

            //si lo encuentro, muestro un error
            if (encontrado) {
                JOptionPane.showMessageDialog(this, "Ya existe un afiliado con ese DNI",
                        "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                //Sino esta en la lista, lo añado
                ventanaFormularioAltaEmpleado.altaAfiliado(new Afiliado(12331, nombreaa.getText(), apellidoaa.getText(),Integer.parseInt(dniaa.getText()) ,sexo , fechaNacimiento, fechaPago));
                JOptionPane.showMessageDialog(this, "Se ha añadido el afiliado",
                        "Añadido", JOptionPane.INFORMATION_MESSAGE);
                
            }
         
            
     } catch (DNIException | NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
     /*} catch (Exception ex) {
           JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
     } */
     }catch(VerficarCampoVacioException cav){
           JOptionPane.showMessageDialog(null, "Debes rellenar todos los campos obligatorios ", "Atencion!", JOptionPane.QUESTION_MESSAGE);
           
    /*} catch (Exception ex) {
           JOptionPane.showMessageDialog(this, " no ingresaste los tipos correcto de datops en las casillas", "Error", JOptionPane.ERROR_MESSAGE);*/
     }
        
    }//GEN-LAST:event_inscribirActionPerformed

    private void sexoaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexoaaActionPerformed
        
    }//GEN-LAST:event_sexoaaActionPerformed

    private void numeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroKeyTyped

        char C= evt.getKeyChar();
     if(Character.isLetter(C))
     {
         getToolkit().beep();
         evt.consume();
         JOptionPane.showMessageDialog(this, "Ingrese solo numeros","Error", JOptionPane.ERROR_MESSAGE);
         numero.setCursor(null);
     }
     else if((int)evt.getKeyChar()>32 && (int)evt.getKeyChar()<=47
             ||(int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=64
             || (int)evt.getKeyChar()>=91 && (int)evt.getKeyChar()<=96
             || (int)evt.getKeyChar()>=123 && (int)evt.getKeyChar()<=255)
    {
         getToolkit().beep();
         evt.consume();
         JOptionPane.showMessageDialog(this, "Ingrese solo numeros","Error", JOptionPane.ERROR_MESSAGE);
         numero.setCursor(null);
     }
     else if(numero.getText().length() >= 4){
         evt.consume();
         getToolkit().beep();
         JOptionPane.showMessageDialog(this, "Longitud maxima de cuatro caracteres","Error", JOptionPane.ERROR_MESSAGE);
         
     }
    }//GEN-LAST:event_numeroKeyTyped

    private void numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroActionPerformed

    private void dniaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dniaaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dniaaActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anioFechaNacimientoaa;
    private javax.swing.JTextField anioFechaPagoaa;
    private javax.swing.JTextField apellidoaa;
    private javax.swing.JTextField diaFechaNacimientoaa;
    private javax.swing.JTextField diaFechaPagoaa;
    private javax.swing.JTextField dniaa;
    private javax.swing.JButton inscribir;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField mesFechaNacimientoaa;
    private javax.swing.JTextField mesFechaPagoaa;
    private javax.swing.JTextField nombreaa;
    private javax.swing.JTextField numero;
    private javax.swing.JComboBox<String> sexoaa;
    // End of variables declaration//GEN-END:variables
}
