/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazGrafica.ventanaAsistenciaMedica;

import clasessimples.Afiliado;
import clasessimples.AsistenciaMedica;
import clasessimples.Chofer;
import clasessimples.Doctor;
import clasessimples.Enfermero;
import clasessimples.Movil;
import excepciones.EmpleadoNoDisponibleExeption;
import java.time.LocalDate;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import sistema.de.emergencia.medica.GestionHospital;

/**
 *
 * @author Miguel
 */
public class AsistenciaMedicaAfiliado extends javax.swing.JFrame {

    GestionHospital llenarAsistenciaMedica;
    AsistenciaMedica a;
    
    
    public AsistenciaMedicaAfiliado(AsistenciaMedica asis) {
        initComponents();
        this.setVisible(false);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        setIconImage (new ImageIcon(getClass().getResource("/Imagenes_Iconos/red-38673_960_720.png")).getImage());
        this.a = asis;
        tipoEnfermedad.setText(a.getEnfemerdad());
        nombreAfiliado.setText(a.getAfiliado().getNombre()+ "  " +a.getAfiliado().getApellido());
        nombreDoctor.setText(a.getDotor().getNombre()+ "  " + a.getDotor().getApellido());
        dniAfiliado.setText(String.valueOf(a.getAfiliado().getDNI()));
        patente.setText(a.getMovil().getPatente());
        //fecha.setText(String.valueOf(am.getFecha()));
        enfemero.setText(a.getEnfermero().getNombre()+ "  " +a.getEnfermero().getApellido());
        nombreChofer.setText(a.getChofer().getNombre()+ "  " +a.getChofer().getApellido());
        numeroAfiliado.setText(String.valueOf(a.getAfiliado().getNumeroAfiliado()));
        this.setVisible(true);
    }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombreDoctor = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombreAfiliado = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        numeroAfiliado = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nombreChofer = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        enfemero = new javax.swing.JLabel();
        patente = new javax.swing.JLabel();
        dniAfiliado = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tipoEnfermedad = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("DOCTOR DESIGNADO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));
        getContentPane().add(nombreDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 269, 10));

        jLabel2.setText("NOMBRE COMPLETO AFILIADO : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 160, -1));
        getContentPane().add(nombreAfiliado, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 221, 10));

        jLabel3.setText("NUMERO AFILIADO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));
        getContentPane().add(numeroAfiliado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 282, 10));

        jLabel4.setText("CHOFER DESIGNADO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));
        getContentPane().add(nombreChofer, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 282, 10));

        jLabel5.setText("ASISTENCIA MEDICA");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jLabel6.setText("ENFERMERO DESIGNADO");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 130, -1));

        jLabel7.setText("PATENTE AMBULANCIA");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel8.setText("DNI AFILIADO");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));
        getContentPane().add(enfemero, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 250, 10));
        getContentPane().add(patente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 230, 10));
        getContentPane().add(dniAfiliado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 270, 10));

        jLabel9.setText("ENFERMEDAD");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 120, -1));
        getContentPane().add(tipoEnfermedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 230, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dniAfiliado;
    private javax.swing.JLabel enfemero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel nombreAfiliado;
    private javax.swing.JLabel nombreChofer;
    private javax.swing.JLabel nombreDoctor;
    private javax.swing.JLabel numeroAfiliado;
    private javax.swing.JLabel patente;
    private javax.swing.JLabel tipoEnfermedad;
    // End of variables declaration//GEN-END:variables
}
