/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazGrafica.ventanaMovil;

import clasessimples.Movil;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import sistema.de.emergencia.medica.GestionHospital;

/**
 *
 * @author REC
 */
public class BajaMovil extends javax.swing.JFrame {
        GestionHospital bajaMovil;
        Movil eliminarMovil;
        
        
    public BajaMovil(GestionHospital gh) {
        this.setVisible(true);
        bajaMovil = gh;
        initComponents();
        setIconImage (new ImageIcon(getClass().getResource("/interfazGrafica/red-38673_960_720.png")).getImage()); //Agrega el icono de la ventana
    }

    private BajaMovil() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        busquedaAuto = new javax.swing.JTextField();
        BotonBuscarAuto = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        mostrarModelo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        mostrarMarca = new javax.swing.JTextField();
        BotonEliminarAuto = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistema de Emergencias Medica");

        jLabel1.setText("INGRESAR EL NUMERO DE PATENTE DEL VEHICULO :");

        busquedaAuto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                busquedaAutoKeyTyped(evt);
            }
        });

        BotonBuscarAuto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Iconos/buscar_1.png"))); // NOI18N
        BotonBuscarAuto.setText("BUSCAR");
        BotonBuscarAuto.setContentAreaFilled(false);
        BotonBuscarAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarAutoActionPerformed(evt);
            }
        });

        jLabel2.setText("MODELO");

        mostrarModelo.setEditable(false);

        jLabel3.setText("MARCA");

        mostrarMarca.setEditable(false);
        mostrarMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarMarcaActionPerformed(evt);
            }
        });

        BotonEliminarAuto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Iconos/borrar_1.png"))); // NOI18N
        BotonEliminarAuto.setText("ELIMINAR");
        BotonEliminarAuto.setContentAreaFilled(false);
        BotonEliminarAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarAutoActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Iconos/TRAS.png"))); // NOI18N
        jButton6.setText("VOLVER");
        jButton6.setContentAreaFilled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(mostrarMarca))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(busquedaAuto)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BotonEliminarAuto)
                            .addComponent(mostrarModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BotonBuscarAuto)
                    .addComponent(jButton6))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(busquedaAuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BotonBuscarAuto))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(mostrarMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(mostrarModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonEliminarAuto)
                    .addComponent(jButton6))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
        //Evento del Boton para mostrar la busqueda del movil
    private void BotonBuscarAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarAutoActionPerformed
        eliminarMovil = bajaMovil.buscarMovil(busquedaAuto.getText());
        if (eliminarMovil != null){
            mostrarMarca.setText(eliminarMovil.getMarca());
            mostrarModelo.setText(eliminarMovil.getModelo());
        } else JOptionPane.showMessageDialog(this," No se ha encontrado el Movil" , "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_BotonBuscarAutoActionPerformed

    private void mostrarMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mostrarMarcaActionPerformed

    private void BotonEliminarAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarAutoActionPerformed
        //bajaMovil.bajaMovil(eliminarMovil);
        
        if(eliminarMovil!= null){
           bajaMovil.bajaMovil(eliminarMovil);
           JOptionPane.showMessageDialog(this, "Se ha eliminado correctamente", "Eliminado", JOptionPane.INFORMATION_MESSAGE);
           this.mostrarMarca.setText("");
           this.mostrarModelo.setText("");
           
        }
        else{
            JOptionPane.showMessageDialog(this," no se pudo eliminar" , "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotonEliminarAutoActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void busquedaAutoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busquedaAutoKeyTyped
     char C= evt.getKeyChar();
     
     if((int)evt.getKeyChar()>32 && (int)evt.getKeyChar()<=47
             ||(int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=64
             || (int)evt.getKeyChar()>=91 && (int)evt.getKeyChar()<=96
             || (int)evt.getKeyChar()>=123 && (int)evt.getKeyChar()<=255)
    {
         getToolkit().beep();
         evt.consume();
         JOptionPane.showMessageDialog(this, "Ingrese solo letras o numeros (AAA111)","Error", JOptionPane.ERROR_MESSAGE);
         busquedaAuto.setCursor(null);
     }
     else if(busquedaAuto.getText().length() >= 6){
         evt.consume();
         getToolkit().beep();
         JOptionPane.showMessageDialog(this, "Longitud maxima de seis caracteres","Error", JOptionPane.ERROR_MESSAGE);
         
     }
    }//GEN-LAST:event_busquedaAutoKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBuscarAuto;
    private javax.swing.JButton BotonEliminarAuto;
    private javax.swing.JTextField busquedaAuto;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField mostrarMarca;
    private javax.swing.JTextField mostrarModelo;
    // End of variables declaration//GEN-END:variables
}
